"""Add Recipe visibility

Revision ID: 919aaca2322f
Revises: 6db3b06cd46f
Create Date: 2026-06-26 16:40:08.445392

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "919aaca2322f"
down_revision: Union[str, None] = "6db3b06cd46f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipes", sa.Column("visibility", sa.String(), server_default="public", nullable=False)
    )
    op.add_column("recipes", sa.Column("owner_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "recipes", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "recipes", type_="foreignkey")
    op.drop_column("recipes", "owner_id")
    op.drop_column("recipes", "visibility")
    # ### end Alembic commands ###
